using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Svm.EntityFrameworkCore.Framework;

namespace Svm.EntityFrameworkCore.Migrations;

[DbContext(typeof(SvmDbContext))]
[Migration("20261001000100_PersonnelSessions")]
internal sealed class PersonnelSessions : Migration
{
    public PersonnelSessions() { }
    protected override void Up(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
        CREATE TABLE iam.users (
          "Id" uuid PRIMARY KEY, "EmployeeNo" varchar(64) NOT NULL,
          "DisplayName" varchar(128) NOT NULL, "PasswordHash" varchar(1024) NOT NULL,
          "IsEnabled" boolean NOT NULL, "MustChangePassword" boolean NOT NULL);
        CREATE UNIQUE INDEX "IX_users_EmployeeNo" ON iam.users ("EmployeeNo");
        CREATE TABLE iam.subject_guards (
          "SubjectId" uuid PRIMARY KEY REFERENCES iam.users("Id") DEFERRABLE INITIALLY DEFERRED, "Revision" bigint NOT NULL CHECK ("Revision" > 0));
        CREATE TABLE iam.sessions (
          "Id" uuid PRIMARY KEY, "SubjectId" uuid NOT NULL REFERENCES iam.users("Id") DEFERRABLE INITIALLY DEFERRED,
          "SecretHash" varchar(64) NOT NULL, "ExpiresAt" timestamptz NOT NULL, "RevokedAt" timestamptz);
        CREATE INDEX "IX_sessions_SubjectId" ON iam.sessions ("SubjectId");
        CREATE INDEX "IX_sessions_ExpiresAt" ON iam.sessions ("ExpiresAt");
        CREATE TABLE iam.permission_catalog ("Operation" varchar(64) PRIMARY KEY, "Global" boolean NOT NULL);
        CREATE TABLE iam.permissions (
          "Id" uuid PRIMARY KEY, "SubjectId" uuid NOT NULL REFERENCES iam.users("Id") DEFERRABLE INITIALLY DEFERRED, "SoftwareId" uuid,
          "Operation" varchar(64) NOT NULL REFERENCES iam.permission_catalog("Operation"));
        CREATE UNIQUE INDEX "IX_permissions_SubjectId_SoftwareId_Operation" ON iam.permissions ("SubjectId", "SoftwareId", "Operation") NULLS NOT DISTINCT;
        CREATE INDEX "IX_permissions_Operation" ON iam.permissions ("Operation");
        CREATE TABLE iam.seed_markers ("Name" varchar(64) PRIMARY KEY, "CompletedAt" timestamptz NOT NULL);
        CREATE TABLE iam.login_limits ("Key" varchar(66) PRIMARY KEY, "Failures" integer NOT NULL CHECK ("Failures" >= 0), "WindowEnd" timestamptz NOT NULL);
        CREATE INDEX "IX_login_limits_WindowEnd" ON iam.login_limits ("WindowEnd");
        CREATE TABLE aud.events (
          "Id" uuid PRIMARY KEY, "OperationId" uuid NOT NULL, "SubjectId" uuid, "ActorKind" varchar(32) NOT NULL,
          "EmployeeNo" varchar(64), "DisplayName" varchar(128), "Operation" varchar(64) NOT NULL,
          "ObjectId" uuid, "Result" varchar(32) NOT NULL, "Reason" varchar(256) NOT NULL,
          "CorrelationId" varchar(128) NOT NULL, "OccurredAt" timestamptz NOT NULL);
        CREATE UNIQUE INDEX "IX_events_OperationId" ON aud.events ("OperationId");
        CREATE INDEX "IX_events_OccurredAt" ON aud.events ("OccurredAt");
        CREATE TABLE framework.data_protection_keys ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "FriendlyName" text, "Xml" text);
        """);
    protected override void Down(MigrationBuilder migrationBuilder) =>
        throw new NotSupportedException("Personnel history requires an explicit recovery plan; automatic downgrade is disabled.");
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        SvmDbContextModelSnapshot.Configure(modelBuilder);
        SvmDbContextModelSnapshot.ConfigurePersonnelV1(modelBuilder);
    }
}
