using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Svm.EntityFrameworkCore.Framework;

namespace Svm.EntityFrameworkCore.Migrations;

[DbContext(typeof(SvmDbContext))]
[Migration("20261007000100_BusOutbox")]
internal sealed class BusOutbox : Migration
{
    public BusOutbox() { }
    protected override void Up(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
        CREATE TABLE framework."InboxState" (
          "Id" bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_InboxState" PRIMARY KEY,
          "MessageId" uuid NOT NULL, "ConsumerId" uuid NOT NULL, "LockId" uuid NOT NULL,
          "RowVersion" bytea, "Received" timestamptz NOT NULL, "ReceiveCount" integer NOT NULL,
          "ExpirationTime" timestamptz, "Consumed" timestamptz, "Delivered" timestamptz, "LastSequenceNumber" bigint,
          CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId","ConsumerId")
        );
        CREATE INDEX "IX_InboxState_Delivered" ON framework."InboxState" ("Delivered");
        CREATE TABLE framework."OutboxState" (
          "OutboxId" uuid CONSTRAINT "PK_OutboxState" PRIMARY KEY, "LockId" uuid NOT NULL, "RowVersion" bytea,
          "Created" timestamptz NOT NULL, "Delivered" timestamptz, "LastSequenceNumber" bigint
        );
        CREATE INDEX "IX_OutboxState_Created" ON framework."OutboxState" ("Created");
        CREATE TABLE framework."OutboxMessage" (
          "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_OutboxMessage" PRIMARY KEY,
          "MessageId" uuid NOT NULL, "ContentType" varchar(256) NOT NULL, "MessageType" text NOT NULL, "Body" text NOT NULL,
          "ConversationId" uuid, "CorrelationId" uuid, "InitiatorId" uuid, "RequestId" uuid,
          "SourceAddress" varchar(256), "DestinationAddress" varchar(256), "ResponseAddress" varchar(256), "FaultAddress" varchar(256),
          "ExpirationTime" timestamptz, "EnqueueTime" timestamptz, "SentTime" timestamptz NOT NULL,
          "Headers" text, "Properties" text, "InboxMessageId" uuid, "InboxConsumerId" uuid, "OutboxId" uuid,
          CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId"
            FOREIGN KEY ("InboxMessageId","InboxConsumerId") REFERENCES framework."InboxState" ("MessageId","ConsumerId"),
          CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId" FOREIGN KEY ("OutboxId") REFERENCES framework."OutboxState" ("OutboxId")
        );
        CREATE INDEX "IX_OutboxMessage_ExpirationTime" ON framework."OutboxMessage" ("ExpirationTime");
        CREATE INDEX "IX_OutboxMessage_EnqueueTime" ON framework."OutboxMessage" ("EnqueueTime");
        CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber"
          ON framework."OutboxMessage" ("InboxMessageId","InboxConsumerId","SequenceNumber");
        CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber" ON framework."OutboxMessage" ("OutboxId","SequenceNumber");
        """);
    protected override void Down(MigrationBuilder migrationBuilder) =>
        throw new NotSupportedException("Pending integration intents require an explicit recovery plan; automatic downgrade is disabled.");
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        SvmDbContextModelSnapshot.Configure(modelBuilder);
        SvmDbContextModelSnapshot.ConfigurePersonnelV1(modelBuilder);
        SvmDbContextModelSnapshot.ConfigureOperationResultsV1(modelBuilder);
        BusOutboxV1Model.Configure(modelBuilder);
    }
}
