<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup />
  <ItemGroup>
    <ProjectReference Include="../../shared/Svm.SharedKernel/Svm.SharedKernel.csproj" />
    <ProjectReference Include="../../services/Svm.Services.Contracts/Svm.Services.Contracts.csproj" />
    <ProjectReference Include="../../core/Svm.Core.Identity/Svm.Core.Identity.csproj" />
    <ProjectReference Include="../../core/Svm.Core.Releases/Svm.Core.Releases.csproj" />
    <ProjectReference Include="../../core/Svm.Core.Packages/Svm.Core.Packages.csproj" />
    <ProjectReference Include="../../core/Svm.Core.Instances/Svm.Core.Instances.csproj" />
    <ProjectReference Include="../../core/Svm.Core.Tasks/Svm.Core.Tasks.csproj" />
    <ProjectReference Include="../../core/Svm.Core.Audit/Svm.Core.Audit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
  </ItemGroup>
</Project>
