import { afterEach, expect, it, vi } from 'vitest'
import { createApp, nextTick, ref } from 'vue'
import { createPinia } from 'pinia'
import { createMemoryHistory, createRouter } from 'vue-router'
import DeploymentsPage from '../src/pages/DeploymentsPage.vue'
import { useSession } from '../src/session'
import { pendingWriteKey } from '../src/mutation'
const sid='11111111-1111-4111-8111-111111111111', iid='22222222-2222-4222-8222-222222222222', selectionId='33333333-3333-4333-8333-333333333333', did='44444444-4444-4444-8444-444444444444'
const caps={ defaultStartLocalTime:'02:00',defaultLatestStartLocalTime:'04:00',timeZone:'Asia/Shanghai',batchSize:2,failureLimit:1,resultWaitSeconds:300,selectionChunkSize:2,maxSelectionMembers:1000,pollRetrySeconds:60 }
const selection={id:selectionId,softwareId:sid,mode:'Explicit',state:'Draft',memberCount:0,receivedChunkCount:0,revision:1}
const deployment={id:did,softwareId:sid,targetReleaseId:'fixture-release',state:'Preparing',window:{notBefore:'2026-10-10T02:00:00Z',latestStart:'2026-10-10T04:00:00Z'},parameters:{batchSize:2,failureLimit:1,resultWaitSeconds:300},selectedCount:1,processedCount:0,acceptedCount:0,rejectedCount:0,resultCounts:{succeeded:0,failed:0,canceled:0,closedUnknown:0,unfinished:0},pauseReasons:[],controlPending:false,revision:1}
const account=(operations=['instance.read','deployment.create','deployment.control','software.read'])=>({authenticated:true,subjectId:did,employeeNo:'TASK-FIXTURE',mustChangePassword:false,csrfToken:'fixture',permissions:operations.map(operation=>({softwareId:sid,operation}))})
const disposers:(()=>void)[]=[]
afterEach(()=>{disposers.splice(0).forEach(f=>f());vi.restoreAllMocks();vi.unstubAllGlobals();document.body.innerHTML=''})
async function settle(){for(let i=0;i<50;i++){await nextTick();await Promise.resolve()}}
function button(text:string){const b=[...document.querySelectorAll('button')].find(x=>x.textContent?.trim()===text);expect(b).toBeTruthy();return b!}
async function mount(operations?:string[]){const router=createRouter({history:createMemoryHistory(),routes:[{path:'/deployments',component:DeploymentsPage},{path:'/other',component:{template:'<p>other</p>'}}]});await router.push('/deployments?softwareId='+sid);const pinia=createPinia();const session=useSession(pinia);session.current=account(operations) as typeof session.current;const pending=ref(false);const root=document.createElement('div');document.body.appendChild(root);const app=createApp({template:'<RouterView />'}).use(pinia).use(router).provide(pendingWriteKey,pending);app.mount(root);disposers.push(()=>app.unmount());await settle();return {router,pending,session}}
function reads(write?:(path:string,o:RequestInit)=>Promise<Response>,read?:(path:string)=>Response|undefined){vi.stubGlobal('fetch',vi.fn(async(path:string,o?:RequestInit)=>{if(o?.method && o.method!=='GET' && write)return write(path,o);const custom=read?.(path);if(custom)return custom;if(path.endsWith('/session'))return Response.json(account());if(path.endsWith('deployment-capabilities'))return Response.json(caps);if(path.includes('/instances?'))return Response.json({items:[{id:iid,deviceName:'任务夹具设备',deviceNo:'TASK-FIXTURE-D',lifecycle:'Active',lastSnapshot:{installationState:'NotInstalled',installedVersion:null}}],nextCursor:null});if(path.endsWith('/deployments/'+did))return Response.json(deployment);if(path.includes('/deployments?'))return Response.json({items:[deployment],nextCursor:null});return Response.json({items:[],nextCursor:null})}))}
it('retains the final operation body and key after response loss without automatically creating another deployment',async()=>{
 const writes:{path:string,headers:HeadersInit|undefined,body:BodyInit|null|undefined}[]=[];let failures=0
 reads(async(path,o)=>{writes.push({path,headers:o.headers,body:o.body});if(path.endsWith('/target-selections'))return Response.json(selection,{status:201});if(path.endsWith('/chunks/0'))return Response.json({...selection,memberCount:1,receivedChunkCount:1,revision:2});if(path.endsWith('/seal')){expect(JSON.parse(o.body as string)).toEqual({expectedRevision:2,chunkCount:1,expectedDistinctCount:1});return Response.json({...selection,state:'Sealed',memberCount:1,receivedChunkCount:1,revision:3})}if(failures++===0)throw new TypeError('lost response');return Response.json(deployment,{status:202})})
 const {pending,router}=await mount();button('选择更新目标').click();await settle();const target=document.querySelector('input[aria-label="选择实例 '+iid+'"]') as HTMLInputElement;target.click();const reason=document.querySelector('textarea[maxlength="256"]') as HTMLTextAreaElement;reason.value='夹具投放原因';reason.dispatchEvent(new Event('input',{bubbles:true}));await settle();(document.querySelector('form') as HTMLFormElement).dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await settle();expect(writes.filter(x=>x.path.endsWith('/deployments'))).toHaveLength(1);expect(pending.value).toBe(true);expect((document.querySelector('fieldset') as HTMLFieldSetElement).disabled).toBe(true);await router.push('/other');expect(router.currentRoute.value.path).toBe('/deployments')
 button('核实原操作').click();await settle();const attempts=writes.filter(x=>x.path.endsWith('/deployments'));expect(attempts).toHaveLength(2);expect(attempts[0]).toEqual(attempts[1]);expect(pending.value).toBe(false);expect(localStorage.length+sessionStorage.length).toBe(0)
})
it('removes task facts and controls when current software read permission is revoked',async()=>{reads();const {session}=await mount();button(did).click();await settle();expect(document.body.textContent).toContain('投放详情');session.current=account([]) as typeof session.current;await settle();expect(document.body.textContent).not.toContain('投放详情');expect(document.body.textContent).toContain('instance.read');expect([...document.querySelectorAll('button')].some(b=>b.textContent==='选择更新目标')).toBe(false)})
it('shows configuration errors without inventing task windows or limits',async()=>{reads();vi.stubGlobal('fetch',vi.fn(async()=>Response.json({code:'CONFIGURATION_INVALID'},{status:503})));await mount();expect(button('选择更新目标').disabled).toBe(true);expect(document.querySelector('form')).toBeNull();expect(document.querySelector('[role="alert"]')).toBeTruthy()})
it('restores a control work response with the original key and body after response loss',async()=>{
 const workId='55555555-5555-4555-8555-555555555555',work={id:workId,softwareId:sid,kind:'Cancel',state:'Pending',stage:'Cancel',cursor:null,processedItems:0,lastErrorCode:null,revision:1}
 const writes:{path:string,headers:HeadersInit|undefined,body:BodyInit|null|undefined}[]=[]
 reads(async(path,o)=>{writes.push({path,headers:o.headers,body:o.body});expect(path).toBe('/api/v1/manage/deployments/'+did+'/cancel');expect(JSON.parse(o.body as string)).toEqual({expectedRevision:1,reason:'夹具核实原取消工作'});if(writes.length===1)throw new TypeError('lost control response');return Response.json({...work,workId,operationId:'fixture-operation'},{status:202})},path=>path.endsWith('/deployment-work/'+workId)?Response.json(work):undefined)
 const {pending}=await mount();button(did).click();await settle();const reason=document.querySelector('input[maxlength="256"]') as HTMLInputElement;reason.value='夹具核实原取消工作';reason.dispatchEvent(new Event('input',{bubbles:true}));await settle();button('取消未获许可任务').click();await settle();expect(writes).toHaveLength(1);expect(pending.value).toBe(true)
 button('核实原操作').click();await settle();expect(writes).toHaveLength(2);expect(writes[0]).toEqual(writes[1]);expect(document.body.textContent).toContain(workId);expect(document.body.textContent).toContain('控制工作');expect(pending.value).toBe(false)
})
