import { afterEach, describe, expect, it, vi } from 'vitest'
import { Blob } from 'node:buffer'
import { createHash } from 'node:crypto'
import { createApp, nextTick, ref } from 'vue'
import { createPinia } from 'pinia'
import { createMemoryHistory, createRouter } from 'vue-router'
import { hashChunks, HASH_CHUNK_BYTES } from '../src/packages/hashChunks'
import { hashFile } from '../src/packages/hashFile'
import ReleasesPage from '../src/pages/ReleasesPage.vue'
import { useSession } from '../src/session'
import { pendingWriteKey } from '../src/mutation'
const sid = '11111111-1111-4111-8111-111111111111', rid = '22222222-2222-4222-8222-222222222222', pid = '33333333-3333-4333-8333-333333333333'
const session = { authenticated: true, subjectId: rid, employeeNo: 'FIXTURE', displayName: '夹具', mustChangePassword: false, csrfToken: 'fixture', serverTime: '2026-10-08T00:00:00Z', permissions: ['software.read', 'release.upload', 'release.disable'].map(operation => ({ softwareId: sid, operation })) }
const release = { id: rid, softwareId: sid, version: '1.0.0', state: 'Staging', changeLevel: 'Patch', changeSummary: '真实更新内容', changeReason: 'fixture', packageId: pid, downloadAvailable: false, createdBy: rid, createdAt: session.serverTime, disabledAt: null, disableReason: null, revision: 1 }
const pkg = { id: pid, releaseId: rid, state: 'Failed', sizeBytes: null, sha256: null, expectedSize: 3, expectedSha256: createHash('sha256').update('abc').digest('hex'), healthyReplicaCount: 0, downloadAvailable: false, downloadPath: null, processingStage: 'UploadFailed', lastErrorCode: 'CHECKSUM_MISMATCH', revision: 3, uploadId: rid, fileName: 'original.zip' }
const disposers: (() => void)[] = []
afterEach(() => { disposers.splice(0).forEach(f => f()); vi.restoreAllMocks(); vi.unstubAllGlobals(); document.body.innerHTML = '' })
async function settle() { for (let i = 0; i < 20; i++) { await nextTick(); await Promise.resolve() } }
async function mount() { const router = createRouter({ history: createMemoryHistory(), routes: [{ path: '/releases', component: ReleasesPage }, { path: '/other', component: { template: '<p>other</p>' } }] }); await router.push('/releases?softwareId=' + sid); const pinia = createPinia(); useSession(pinia).current = session; const root = document.createElement('div'); document.body.appendChild(root); const pending = ref(false); const app = createApp({ template: '<RouterView />' }).use(pinia).use(router).provide(pendingWriteKey, pending); app.mount(root); disposers.push(() => app.unmount()); await settle(); return { pending, router } }
function button(text: string) { const b = [...document.querySelectorAll('button')].find(x => x.textContent?.trim() === text); expect(b).toBeTruthy(); return b! }
function mockReads(writes?: (p: string, o: RequestInit) => Promise<Response>) { vi.stubGlobal('fetch', vi.fn(async (p: string, o?: RequestInit) => { if (o?.method && o.method !== 'GET' && writes) return writes(p, o); if (p.endsWith('/session')) return Response.json(session); if (p.endsWith('/capabilities')) return Response.json({ maxPackageBytes: 10000000 }); if (p.endsWith('/software/' + sid)) return Response.json({ id: sid, code: 'FIXTURE', name: '夹具视觉', category: 'Vision' }); if (p.includes('test-evidence') || p.includes('audit-events')) return Response.json({ items: [], nextCursor: null }); if (p.endsWith('/releases/' + rid)) return Response.json(release); if (p.endsWith('/packages/' + pid)) return Response.json(pkg); return Response.json({ items: p.includes('Formal') ? [] : [release], nextCursor: null }) })) }
describe('package hashing and version interactions', () => {
  it('hashes bounded 1 MiB slices independently of browser chunk timing', async () => {
    const bytes = new Uint8Array(HASH_CHUNK_BYTES * 2 + 73); for (let i = 0; i < bytes.length; i++) bytes[i] = i % 251
    const blob = new Blob([bytes]), progress: number[] = [], slices: number[] = []; const input = { size: blob.size, slice: (a: number, b: number) => { slices.push(b - a); return blob.slice(a, b) } } as globalThis.Blob
    expect(await hashChunks(input, n => progress.push(n))).toBe(createHash('sha256').update(bytes).digest('hex')); expect(slices.every(n => n === HASH_CHUNK_BYTES)).toBe(true); expect(progress).toEqual([HASH_CHUNK_BYTES, HASH_CHUNK_BYTES * 2, bytes.length])
  })
  it('cancel stops hashing before subsequent slices and returns no digest', async () => { const abort = new AbortController(); const blob = new Blob([new Uint8Array(HASH_CHUNK_BYTES * 3)]); const slices = vi.spyOn(blob, 'slice'); await expect(hashChunks(blob as unknown as globalThis.Blob, () => abort.abort(), abort.signal)).rejects.toThrow(); expect(slices).toHaveBeenCalledTimes(1) })
  it('worker cancellation terminates the worker and removes late callbacks', async () => { const terminate = vi.fn(); class Worker { onmessage: unknown; onerror: unknown; terminate = terminate; postMessage() {} }; vi.stubGlobal('Worker', Worker); const abort = new AbortController(); const task = hashFile(new File(['abc'], 'fixture.zip'), vi.fn(), abort.signal); abort.abort(); await expect(task).rejects.toMatchObject({ name: 'AbortError' }); expect(terminate).toHaveBeenCalledOnce() })
  it('shows real empty formal view, staging facts and reupload without registering another version', async () => { mockReads(); await mount(); expect(document.body.textContent).toContain('真实更新内容'); button('1.0.0').click(); await settle(); expect(document.body.textContent).toContain('接收失败'); expect(document.querySelector('a[download]')).toBeNull(); button('重传原版本安装包').click(); await settle(); expect(document.body.textContent).toContain(rid); expect(document.querySelector('input[type=file]')).not.toBeNull(); button('取消').click(); button('正式版本').click(); await settle(); expect(document.body.textContent).toContain('尚无正式版本') })
  it('unknown disable retains original key/body and guards navigation without another operation', async () => { const writes: RequestInit[] = []; mockReads(async (_p, o) => { writes.push(o); if (writes.length === 1) throw new TypeError('fixture lost response'); return Response.json({ ...release, state: 'Disabled', revision: 2 }) }); const { pending, router } = await mount(); button('1.0.0').click(); await settle(); const reason = document.querySelector('input[maxlength="256"]') as HTMLInputElement; reason.value = 'fixture disable'; reason.dispatchEvent(new Event('input', { bubbles: true })); await settle(); button('停用版本').click(); await settle(); expect(pending.value).toBe(true); await router.push('/other'); expect(router.currentRoute.value.path).toBe('/releases'); button('核实原操作').click(); await settle(); expect(writes).toHaveLength(2); expect(writes[1].headers).toEqual(writes[0].headers); expect(writes[1].body).toEqual(writes[0].body); expect(pending.value).toBe(false) })
})
