<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../hosts/Svm.HttpApi/Svm.HttpApi.csproj" />
    <ProjectReference Include="../../services/Svm.Application/Svm.Application.csproj" />
    <ProjectReference Include="../../services/Svm.Services.Contracts/Svm.Services.Contracts.csproj" />
    <ProjectReference Include="../../services/Svm.Services.CrossCutting/Svm.Services.CrossCutting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" PrivateAssets="all" />
  </ItemGroup>
</Project>
